energysense/energysense/urls.py
from django.conf.urls import patterns, include, url
# from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'energysense.views.home', name='home'),
    url(r'^login/$', 'accounts.views.login_user', name='login'),
    url(r'^logout/$', 'accounts.views.logout_user', name='logout'),
    url(r'^register/$', 'accounts.views.register', name='register'),
    url(r'^monitor/', include('monitor.urls', namespace='monitor')),
)

energysense/monitor/urls.py
from django.conf.urls import patterns, url
from monitor import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^home_iframe/', views.home_iframe, name = 'home_iframe'),
    url(r'^data$', views.data, name='data'),
    url(r'^linewithfocuschart/', views.linewithfocuschart, name='linewithfocuschart'),
)

energysense/monitor/models.py
from django.db import models
#This model map each tale in database to a class in django framwork

class Sensor(models.Model):
    sensor_id = models.IntegerField(primary_key=True)
    last_connected_time = models.DateTimeField()
    initial_energy = models.FloatField()
    remaining_energy = models.FloatField()
    is_base_station = models.IntegerField()
    last_voltage = models.FloatField()
    x = models.IntegerField()
    y = models.IntegerField()

class User_Sensor(models.Model):
    user_id = models.IntegerField()
    sensor_id = models.IntegerField()

class Energymonitor(models.Model):
    nodeid = models.IntegerField(db_column='NodeID') # Field name made lowercase.
    time = models.DateTimeField(db_column='Time') # Field name made lowercase.
    voltage = models.FloatField(db_column='Voltage') # Field name made lowercase.
    cumcurr = models.FloatField(db_column='CumCurr') # Field name made lowercase.
    data = models.CharField(db_column='Data', max_length=40) # Field name made lowercase.
    exp = models.IntegerField(db_column='Experiment')
    class Meta:
        managed = False
        db_table = 'EnergyMonitor'

class Topology(models.Model):
    sensorID1 = models.IntegerField()
    sensorID2 = models.IntegerField()

class ActiveBS(models.Model):
    starttime = models.DateTimeField(db_column = 'StartTime')
    endtime = models.DateTimeField(db_column = 'EndTime')
    nodeid = models.IntegerField(db_column = 'NodeID')
    exp = models.IntegerField(db_column = 'Experiment')
    class Meta:
        managed = False
        db_table = 'ActiveBS'

energysense/monitor/views.py
#this model renders the responding web page

from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.core.context_processors import csrf
import sqlweb

#render home.html
@login_required
def home(request):
    return render_to_response('monitor/home.html', {})

#render linewithfocuschart.html
@login_required
def linewithfocuschart(request):
    (time, voltage, current, userSensors, selectedSens, exps, selectedExp,slope,activeTime) = sqlweb.getData(request)
    tooltip_date = "%d %b %Y %H:%M:%S %p"
    extra_seriev = {"tooltip": {"y_start": "", "y_end": ""},
                   "date_format": tooltip_date}
    extra_seriei = {"tooltip": {"y_start": "", "y_end": ""},
                   "date_format": tooltip_date}

    chartdatav = {'x': time}
    for i in range(0,len(selectedSens)):
        chartdatav['name'+str(i+1)] = 'Voltage-'+str(selectedSens[i])
        chartdatav['y'+str(i+1)] = voltage[i]
        chartdatav['extra'+str(i+1)] = extra_seriev

    chartdatai = {'x': time}
    for i in range(0,len(selectedSens)):
        chartdatai['name'+str(i+1)] = 'Current-'+str(selectedSens[i])
        chartdatai['y'+str(i+1)] = current[i]
        chartdatai['extra'+str(i+1)] = extra_seriei

    charttypev = "lineWithFocusChart"
    charttypei = "lineWithFocusChart"
    chartcontainerv = 'linewithfocuschart_containerv'  # container name
    chartcontaineri = 'linewithfocuschart_containeri'

    data = {
        'charttypev': charttypev,
        'charttypei': charttypei,
        'chartdatav': chartdatav,
        'chartdatai': chartdatai,
        'chartcontainerv': chartcontainerv,
        'chartcontaineri': chartcontaineri,
        'extrav': {
            'x_is_date': True,
            'x_axis_format': '%d %b %Y %H',
            'tag_script_js': True,
            'jquery_on_ready': True,
        },
         'extrai': {
            'x_is_date': True,
            'x_axis_format': '%d %b %Y %H',
            'tag_script_js': True,
            'jquery_on_ready': True,
        },
        'userSensors':userSensors,
        'selectedSens':selectedSens,
        'exps':exps,
        'selectedExp':selectedExp,
        'slopes': slope,
        'activeTime':activeTime
    }
    data.update(csrf(request))
    return render_to_response('monitor/linewithfocuschart.html', data)

@login_required
def data(request):
    return render_to_response('monitor/data.html', {})

#render home_iframe.html
@login_required
def home_iframe(request):
    if request.method == 'POST':
        addid = request.POST.getlist('add', False)
        if addid != False:
            sqlweb.addSensor(addid, request)
        delid = request.POST.getlist('delete', False)
        if delid != False:
             sqlweb.delSensor(delid, request)
    (userSensors, allSensors, topology) = sqlweb.getSensorsInfo(request)
    userSensorsID = [us.sensor_id for us in userSensors]
    notUserSensors = [s for s in allSensors if s.sensor_id not in userSensorsID]
    userSensors = [s for s in allSensors if s.sensor_id in userSensorsID]
    data = {
        'allSensors':allSensors,
        'userSensors':userSensors,
        'notUserSensors':notUserSensors,
        'topology':topology
    }
    data.update(csrf(request))
    return render_to_response('monitor/home_iframe.html', data)

energysense/monitor/templates/monitor/data.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Energy Sense Data</title>
	<link rel="stylesheet" href="../../../static/css/style.css" type="text/css">
    <script language="javascript" type="text/javascript">
        function resizeIframe(obj) {
            obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
        }
    </script>
</head>
<body>
	<div id="background-yellow">
		background
	</div>
	<div class="page">
		<div class="about-page">
             <div class = "header">
                <ul>
                    <li>
                        <a href="/logout/">Logout</a>
                    </li>
                </ul>
            </div>
			<div class="sidebar">
				<ul>
					<li class="home">
						<a href="{% url "monitor:home" %}">Sensors</a>
					</li>
					<li class="selected about">
						<a href="{% url "monitor:data" %}">Data</a>
					</li>
				</ul>
			</div>
			<div class="body">
				<div class="content-about">
                   	<div>
                        <iframe src="{% url 'monitor:linewithfocuschart' %}" frameBorder="0" width="1200px" scrolling = "no" onload='javascript:resizeIframe(this);' ></iframe>
					</div>
                </div>

				<div class="footer">

				</div>
			</div>
		</div>
	</div>
</body>
</html>

energysense/monitor/templates/monitor/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Energy Sense</title>
	<link rel="stylesheet" href="../../../static/css/style.css" type="text/css">
    <script language="javascript" type="text/javascript">
        function resizeIframe(obj) {
            obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
        }
    </script>
</head>
<body>
	<div id="background-green">
		background
	</div>
	<div class="page">

		<div class="home-page">
            <div class = "header">
                <ul>
                    <li>
                        <a href="/logout/">Logout</a>
                    </li>
                </ul>
            </div>
			<div class="sidebar">
				<ul>
					<li class="selected home">
						<a href="{% url "monitor:home" %}">Sensors</a>
					</li>
					<li class="about">
						<a href="{% url "monitor:data" %}">Data</a>
					</li>

				</ul>
			</div>
			<div class="body">

				<div class="content-home">
					<div>
						<div>
							 <iframe name = "chart" src = "{% url 'monitor:home_iframe' %}" frameBorder="0" width="1200px" scrolling = "no" onload='javascript:resizeIframe(this);'></iframe>
						</div>
					</div>
				</div>
				<div class="footer">
				</div>
			</div>
		</div>
	</div>
</body>
</html>

energysense/monitor/templates/monitor/home_iframe.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        th, td {
            padding: 5px;
            text-align: left;
        }

    </style>

</head>
<body>
    <div style="width: 50%;float: left" >
        <!--table of all sensors-- >
        <div style="height: 50%;">
            All Sensors:<br>
            <table style="width:100%">
                <tr>
                    <th>Sensor ID</th>
                    <th>Last Connected Time</th>
                    <th>Base Station</th>
                </tr>
                {% for sensor in allSensors %}
                <tr>
                    <td>{{ sensor.sensor_id }}</td>
                    <td>{{ sensor.last_connected_time }}</td>
                    <td>
                        {% if sensor.is_base_station == 1 %}
                            Yes
                        {% else %}
                            No
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
            <br>
        </div>
        <!--form to add or delete user's sensors-- >
        <div style="border: 1px solid black;padding: 5px">
            <form url = "{% url 'monitor:home_iframe' %}" method = "post">{% csrf_token %}
                Add Sensors:
                <br>
                {% for sensor in notUserSensors %}
                    <input type="checkbox" name="add" value="{{ sensor.sensor_id }}"> {{ sensor.sensor_id }}
                {% endfor %}
                <br>
                Delete Sensors:
                <br>
                {% for sensor in userSensors %}
                    <input type="checkbox" name="delete" value="{{ sensor.sensor_id }}"> {{ sensor.sensor_id }}
                {% endfor %}
                <br>
                <input type="submit">
            </form>
        </div>
    </div>
    <!--display the network-->
    <div style="width: 500px ;height:700px;float: left;margin: 10px 0px 0px 50px" >
        <div style = "margin: 0px 0px 30px 0px">Sensor Network(red nodes are your sensors) </div>
        <div style="width: 500px;height:500px" id="topology_container"></div>
    </div>
    <script src="{% static "components/sigma/sigma.min.js" %}"></script>
    <script>
        var s = new sigma('topology_container');

        {% for us in userSensors %}
            s.graph.addNode({
                id:'{{ us.sensor_id }}',
                label:'Sensor {{ us.sensor_id  }}',
                x:{{ us.x }},
                y:{{ us.y }},
                size: 1,
                color: '#f00'
            });
        {% endfor %}


        {% for us in notUserSensors %}
            s.graph.addNode({
                id:'{{ us.sensor_id }}',
                label:'Sensor {{ us.sensor_id  }}',
                x:{{ us.x }},
                y:{{ us.y }},
                size: 1,
                color: '#000'
            });
        {% endfor %}

        {% for t in topology %}
            s.graph.addEdge({
                id:'{{ t.id }}',
                source:'{{ t.sensorID1 }}',
                target:'{{ t.sensorID2 }}',
                color:'#000'
            });
        {% endfor %}

        s.refresh();
    </script>


</body>
</html>

energysense/monitor/templates/monitor/linewithfocuschart.html
{% load nvd3_tags %}
<head>
    {% include_chart_jscss %}
    {# Jquery CDN : Needed when using jquery_on_ready=True #}
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
    <script type="text/javascript" src="../../../static/timeline/timeline.js"></script>
    <link rel="stylesheet" type="text/css" href="../../../static/css/timeline.css">
    {% load_chart charttypev chartdatav chartcontainerv extrav %}
    {% load_chart charttypei chartdatai chartcontaineri extrai %}
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        th, td {

            padding: 1px;
            text-align: left;
        }
        p {
            line-height: 200%;
        }
        div.active {
            height: 10px;
        }
    </style>
    <script type="text/javascript">
        var timeline = null;

        google.load("visualization", "1");

        // Set callback to run when API is loaded
        google.setOnLoadCallback(drawVisualization);

        // Called when the Visualization API is loaded.
        function drawVisualization() {
            // Create and populate a data table.
            var data = new google.visualization.DataTable();
            data.addColumn('datetime', 'start');
            data.addColumn('datetime', 'end');
            data.addColumn('string', 'content');
            data.addColumn('string', 'group');

            var order = 1;
            {% for bs, lis in activeTime.items %}
                {% for sy,smo,sd,sh,smi,ss,ey,emo,ed,eh,emi,es in lis %}
                    var start = new Date({{ sy }},{{ smo }},{{ sd }},{{ sh }},{{ smi }},{{ ss }});
                    var end = new Date({{ ey }},{{ emo }},{{ ed }},{{ eh }},{{ emi }},{{ es }});
                    var activeText = "<div class='active'>" + "</div>";
                    var bsText = "Base Station " + {{ bs }};
                    data.addRow([start, end, activeText, bsText]);
                {% endfor %}
            {% endfor %}


            // specify options
            var options = {
                width:  "100%",
                //height: "300px",
                height: "auto",
                layout: "box",
                editable: false,
                eventMargin: 5,  // minimal margin between events
                eventMarginAxis: 0, // minimal margin beteen events and the axis
                showMajorLabels: false,
                axisOnTop: true,
                // groupsWidth : "200px",
                groupsChangeable : true,
                groupsOnRight: false,
                stackEvents: false
            };

            // Instantiate our timeline object.
            timeline = new links.Timeline(document.getElementById('activeTimeLine'), options);

            // Draw our timeline with the created data and options
            timeline.draw(data);
        }
    </script>
</head>
<body>
    <!--form which allows user to choose the time interval, sensors and test -->
    <form url = "{% url 'monitor:linewithfocuschart' %}" method = "post">{% csrf_token %}
        <p>
            Starttime: <input type="date" name="start" value="2014-11-01">
            Endtime:<input type="date" name="end" value="2014-11-30"><br>
            Select Sensors:
            {% for id in userSensors %}
                     <input type="checkbox" name="sensorID" value="{{ id }}"> {{ id }}
            {% endfor %}
            <br>
            Which Test:
            <select name = 'experiment'>
                {% for i in exps %}
                    {% if i == selectedExp %}
                        {% if i == 0%}
                            <option value="{{ selectedExp }}" selected = "selected">Random</option>
                        {% elif i == 1 %}
                            <option value="{{ selectedExp }}" selected = "selected">Active One Base Station</option>
                        {% elif i == 2 %}
                            <option value="{{ selectedExp }}" selected = "selected">Active All Base Stations</option>
                        {% else %}
                            <option value="{{ selectedExp }}" selected = "selected">Moving Base Stations</option>
                        {% endif %}

                    {% else %}
                        {% if i == 0%}
                            <option value="{{ i }}">Random</option>
                        {% elif i == 1 %}
                            <option value="{{ i }}">Active One Base Station</option>
                        {% elif i == 2 %}
                            <option value="{{ i }}">Active All Base Stations</option>
                        {% else %}
                            <option value="{{ i }}">Moving Base Stations</option>
                        {% endif %}

                    {% endif %}
                {% endfor %}
            </select><br>
            <input type="submit">
        </p>
    </form>

    <!--display the activated time for each base station-->
    {% if activeTime.keys %}
        <div style="float: left;width: 100%;padding: 0 0 30px 0">
             Activated time of each base station:
            <div  id = "activeTimeLine" ></div>
        </div>
    {% endif %}

    <!--voltage-->
    <div style="float: left; width: 50%;padding: 0px 0px 30px 0px">
        {% include_container chartcontainerv 400 '100%' %}
    </div>

    <!--cumulative current-->
    <div style="float: left; width: 50%;padding: 0px 0px 30px 0px">
        {% include_container chartcontaineri 400 '100%' %}
    </div>

    <!--cumulative current decrease rate for each chosen sensor-->
{#    <div style="float: left; width: 100%; padding: 30px">#}
{#        <br>#}
{#        {% for id, slope in slopes.items %}#}
{#            Sensor {{ id }}#}
{#             <table style="width:100%">#}
{#                <tr>#}
{#                    <th>Test</th>#}
{#                    <th>Slope</th>#}
{#                </tr>#}
{#                {% for key, val in slope.items %}#}
{#                <tr>#}
{#                    {% if key == 0 %}#}
{#                        <td>Random</td>#}
{#                    {% elif key == 1 %}#}
{#                        <td>One BaseStation</td>#}
{#                    {% elif key == 2%}#}
{#                        <td>All BaseStations</td>#}
{#                    {% else %}#}
{#                        <td>Moving BaseStations</td>#}
{#                    {% endif %}#}
{#                    <td>{{ val }} </td>#}
{#                </tr>#}
{#                {% endfor %}#}
{#              </table>#}
{#        {% endfor %}#}
{#    </div>#}
    <div style="float: left; width: 90%; padding: 30px">
        <br>
        {% if selectedSens%}
            <table>
                <tr>
                    <th>Test</th>
                    {% for id in selectedSens %}
                        <th>Sensor-{{ id }}</th>
                    {% endfor %}
                </tr>

                {% for exp, slopelis in slopes.items %}
                    <tr>
                        {% if exp == 0 %}
                            <td>Random</td>
                        {% elif exp == 1 %}
                            <td>One BaseStation</td>
                        {% elif exp == 2%}
                            <td>All BaseStations</td>
                        {% else %}
                            <td>Moving BaseStations</td>
                        {% endif %}
                        {% for slope in slopelis %}
                            <td>{{ slope }} </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    </div>
</body>